abstract class AppStrings {
  static const String ar = 'ar',
      en = 'en',
      all = 'All',
      arabic = 'Arabic',
      english = 'English',
      language = 'Language',
      sortedBy = 'Sorted By',
      sortingType = 'Sorting Type',
      newWord = 'New Word',
      done = 'Done',
      allWords = "All Words",
      englishOnly = "English Only",
      arabicOnly = "Arabic Only",
      time = 'time',
      wordLength = 'Word Length',
      ascending = 'Ascending',
      descending = 'Descending',
      thisFieldHasNotEmpty = 'this field has not be empty',
      isNotRightChar = 'is not right character',
      isNotEnglishChar = 'is not right English character',
      isNotArabicChar = 'is not right Arabic character',
      thereIsProblem = 'there is a problem, try again';
}
